spring:
  application:
    name: discovery-service
#  cloud:
#    config:
#      uri: http://localhost:8088

server:
  port: 8061    
  
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
  